version: '2'
services:
  mumble_app:
    image: zaggash/docker-murmur
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker_config/mumble_app:/config
    ports:
      - 64738:64738/tcp
      - 64738:64738/udp

